In [11]:
import pandas as pd

In [12]:
data = pd.read_csv('./Datasets/used_car_dataset.csv')
data

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [13]:
data.dtypes

name          str
company       str
year          str
Price         str
kms_driven    str
fuel_type     str
dtype: object

# Cleaning Data

## Cleaning Name Column & Turning to Numbers

In [16]:
data['name']  = data['name'].astype('category').cat.codes
data

     name    company  year          Price  kms_driven fuel_type
0     154    Hyundai  2007         80,000  45,000 kms    Petrol
1     204   Mahindra  2006       4,25,000      40 kms    Diesel
2     254     Maruti  2018  Ask For Price  22,000 kms    Petrol
3     143    Hyundai  2014       3,25,000  28,000 kms    Petrol
4      61       Ford  2014       5,75,000  36,000 kms    Diesel
..    ...        ...   ...            ...         ...       ...
887   406       Tara  zest       3,10,000         NaN       NaN
888   460       Tata  2018       2,60,000  27,000 kms    Diesel
889   212   Mahindra  2013       3,90,000  40,000 kms    Diesel
890    82      Honda  2014       1,80,000      Petrol       NaN
891    33  Chevrolet  2014       1,60,000      Petrol       NaN

[892 rows x 6 columns]

## Cleaning Company Column