In [152]:
import pandas as pd
import numpy as np

In [153]:
data = pd.read_csv('./Datasets/used_car_dataset.csv')
data

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [154]:
data.dtypes

name          str
company       str
year          str
Price         str
kms_driven    str
fuel_type     str
dtype: object

# Cleaning Data

## Cleaning Name Column & Turning to Numbers

In [155]:
data['name']  = data['name'].astype('category').cat.codes
data

     name    company  year          Price  kms_driven fuel_type
0     154    Hyundai  2007         80,000  45,000 kms    Petrol
1     204   Mahindra  2006       4,25,000      40 kms    Diesel
2     254     Maruti  2018  Ask For Price  22,000 kms    Petrol
3     143    Hyundai  2014       3,25,000  28,000 kms    Petrol
4      61       Ford  2014       5,75,000  36,000 kms    Diesel
..    ...        ...   ...            ...         ...       ...
887   406       Tara  zest       3,10,000         NaN       NaN
888   460       Tata  2018       2,60,000  27,000 kms    Diesel
889   212   Mahindra  2013       3,90,000  40,000 kms    Diesel
890    82      Honda  2014       1,80,000      Petrol       NaN
891    33  Chevrolet  2014       1,60,000      Petrol       NaN

[892 rows x 6 columns]

## Cleaning Company Column

In [156]:
data['company'] = data['company'].astype('category').cat.codes
data

     name  company  year          Price  kms_driven fuel_type
0     154       14  2007         80,000  45,000 kms    Petrol
1     204       20  2006       4,25,000      40 kms    Diesel
2     254       21  2018  Ask For Price  22,000 kms    Petrol
3     143       14  2014       3,25,000  28,000 kms    Petrol
4      61       11  2014       5,75,000  36,000 kms    Diesel
..    ...      ...   ...            ...         ...       ...
887   406       31  zest       3,10,000         NaN       NaN
888   460       32  2018       2,60,000  27,000 kms    Diesel
889   212       20  2013       3,90,000  40,000 kms    Diesel
890    82       13  2014       1,80,000      Petrol       NaN
891    33        6  2014       1,60,000      Petrol       NaN

[892 rows x 6 columns]

## Turning Year col to int

In [157]:
data["year"] = pd.to_numeric(data['year'], errors='coerce')
data

     name  company    year          Price  kms_driven fuel_type
0     154       14  2007.0         80,000  45,000 kms    Petrol
1     204       20  2006.0       4,25,000      40 kms    Diesel
2     254       21  2018.0  Ask For Price  22,000 kms    Petrol
3     143       14  2014.0       3,25,000  28,000 kms    Petrol
4      61       11  2014.0       5,75,000  36,000 kms    Diesel
..    ...      ...     ...            ...         ...       ...
887   406       31     NaN       3,10,000         NaN       NaN
888   460       32  2018.0       2,60,000  27,000 kms    Diesel
889   212       20  2013.0       3,90,000  40,000 kms    Diesel
890    82       13  2014.0       1,80,000      Petrol       NaN
891    33        6  2014.0       1,60,000      Petrol       NaN

[892 rows x 6 columns]

## Cleaning Price

In [ ]:
data["Price"] = (
    data["Price"]
    .astype(str)  # ensure string (handles NaN)
    .str.replace(",", "", regex=False)  # remove all dots
    .apply(pd.to_numeric, errors="coerce")  # convert to float, invalid -> NaN
)

     name  company    year    Price  kms_driven fuel_type
0     154       14  2007.0   8000.0  45,000 kms    Petrol
1     204       20  2006.0  42500.0      40 kms    Diesel
2     254       21  2018.0      NaN  22,000 kms    Petrol
3     143       14  2014.0  32500.0  28,000 kms    Petrol
4      61       11  2014.0  57500.0  36,000 kms    Diesel
..    ...      ...     ...      ...         ...       ...
887   406       31     NaN  31000.0         NaN       NaN
888   460       32  2018.0  26000.0  27,000 kms    Diesel
889   212       20  2013.0  39000.0  40,000 kms    Diesel
890    82       13  2014.0  18000.0      Petrol       NaN
891    33        6  2014.0  16000.0      Petrol       NaN

[892 rows x 6 columns]

In [ ]:

data["Price"] = data["Price"] / 10

In [160]:
price_mean = data["Price"].mean().round()

data["Price"] = data["Price"].fillna(price_mean)

data

     name  company    year    Price  kms_driven fuel_type
0     154       14  2007.0   8000.0  45,000 kms    Petrol
1     204       20  2006.0  42500.0      40 kms    Diesel
2     254       21  2018.0  40469.0  22,000 kms    Petrol
3     143       14  2014.0  32500.0  28,000 kms    Petrol
4      61       11  2014.0  57500.0  36,000 kms    Diesel
..    ...      ...     ...      ...         ...       ...
887   406       31     NaN  31000.0         NaN       NaN
888   460       32  2018.0  26000.0  27,000 kms    Diesel
889   212       20  2013.0  39000.0  40,000 kms    Diesel
890    82       13  2014.0  18000.0      Petrol       NaN
891    33        6  2014.0  16000.0      Petrol       NaN

[892 rows x 6 columns]